version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SergeWeber2303
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: SergeWeber2303
      DB_NAME: testdb
      DB_PORT: 5432

volumes:
  postgres_data:
