#!/bin/sh

echo "⏳ En attente de PostgreSQL sur le port 5432..."

# On attend que PostgreSQL réponde
until nc -z db 5432; do
  sleep 1
done

echo "✅ PostgreSQL est prêt, démarrage du backend"
node server.js
